FormKey: 079840:SexLab.esm
EditorID: SexLabConfigurationMenu
FormVersion: 43
VirtualMachineAdapter:
  Scripts:
  - Name: sslConfigMenu
    Properties:
    - MutagenObjectType: ScriptObjectProperty
      Name: ActorLib
      Object: 000D62:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: AnimSlots
      Object: 0639DF:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: Config
      Object: 000D62:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: CreatureSlots
      Object: 0664FB:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: ExpressionSlots
      Object: 0664FB:SexLab.esm
    - MutagenObjectType: ScriptStringProperty
      Name: ModName
      Data: SexLab
    - MutagenObjectType: ScriptObjectProperty
      Name: PlayerRef
      Object: 000014:Skyrim.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: SexLab
      Object: 000D62:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: Stats
      Object: 000D62:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: ThreadLib
      Object: 000D62:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: ThreadSlots
      Object: 000D62:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: VoiceSlots
      Object: 0664FB:SexLab.esm
  FileName: ''
  Aliases:
  - Property:
      Name: ''
      Object: 079840:SexLab.esm
      Alias: 0
    Scripts:
    - Name: SKI_PlayerLoadGameAlias
Name:
  TargetLanguage: English
  Value: SexLab MCM
Flags:
- StartGameEnabled
- 0x10
- RunOnce
Priority: 100
QuestFormVersion: 35
Filter: SexLab\
NextAliasID: 1
Aliases:
- Name: PlayerAlias
  Flags: []
  ForcedReference: 000014:Skyrim.esm
  VoiceTypes: Null
