FormKey: 03E3FA:SexLab.esm
EditorID: SexLabQuestConfiguration
FormVersion: 43
VirtualMachineAdapter:
  Scripts:
  - Name: sslConfigMenu
    Properties:
    - MutagenObjectType: ScriptObjectProperty
      Name: Config
      Object: 000D62:SexLab.esm
    - MutagenObjectType: ScriptStringProperty
      Name: ModName
      Data: SexLab
    - MutagenObjectType: ScriptObjectProperty
      Name: PlayerRef
      Object: 000014:Skyrim.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: SexLab
      Object: 000D62:SexLab.esm
  FileName: ''
  Aliases:
  - Property:
      Name: ''
      Object: 03E3FA:SexLab.esm
      Alias: 0
    Scripts:
    - Name: SKI_PlayerLoadGameAlias
Name:
  TargetLanguage: English
  Value: SexLab MCM
Flags:
- StartGameEnabled
- 0x10
- RunOnce
Priority: 90
QuestFormVersion: 31
Filter: SexLab\
NextAliasID: 1
Aliases:
- Name: PlayerAlias
  Flags: []
  ForcedReference: 000014:Skyrim.esm
  VoiceTypes: Null
