FormKey: 03E3FA:SexLab.esm
EditorID: SexLabQuestConfiguration
FormVersion: 43
VirtualMachineAdapter:
  Scripts:
  - Name: sslConfigMenu
    Properties:
    - MutagenObjectType: ScriptObjectProperty
      Name: aCalypsStrapon
      Object: 01A22A:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: ActorLib
      Object: 03CE6B:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: ActorSlots
      Object: 03CE6B:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: AnimLib
      Object: 03CE6C:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: AnimSlots
      Object: 03CE6C:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: ControlLib
      Object: 054227:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: CreatureAnimSlots
      Object: 044A6C:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: ExpressionLib
      Object: 04C63D:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: ExpressionSlots
      Object: 04C63D:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: mCleanSystemFinish
      Object: 020439:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: mNoSKSE
      Object: 014BB5:SexLab.esm
    - MutagenObjectType: ScriptStringProperty
      Name: ModName
      Data: SexLab
    - MutagenObjectType: ScriptObjectProperty
      Name: mOldSKSE
      Object: 014BB3:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: mOldSkyrim
      Object: 014BB4:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: mSystemDisabled
      Object: 02043B:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: mSystemUpdated
      Object: 0321F8:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: PlayerRef
      Object: 000014:Skyrim.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: SexLab
      Object: 000D62:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: SexLabDebugSpell
      Object: 0073CC:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: Stats
      Object: 03CE6B:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: ThreadLib
      Object: 03CE6E:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: ThreadSlots
      Object: 03CE6E:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: VoiceLib
      Object: 03DE97:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: VoiceSlots
      Object: 03DE97:SexLab.esm
  FileName: ''
  Aliases:
  - Property:
      Name: ''
      Object: 03E3FA:SexLab.esm
      Alias: 0
    Scripts:
    - Name: SKI_PlayerLoadGameAlias
Name:
  TargetLanguage: English
  Value: SexLab Configuration
Flags:
- StartGameEnabled
- 0x10
- RunOnce
Priority: 90
QuestFormVersion: 34
Filter: SexLab\
NextAliasID: 1
Aliases:
- Name: PlayerAlias
  Flags: []
  ForcedReference: 000014:Skyrim.esm
  VoiceTypes: Null
